# 
# GitLab Serverless Runner Manager
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



stages:
  - release


variables:
    # Fix wrong permissions for application image and instance user data due to runner setting "umask 0000" before
    # cloning the repository.
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 'true'
    GIT_STRATEGY: clone



# 
# Jobs
#-----------------------------------------------------------------------------------------------------------------------
gitlabRegistry:
    stage: release
    
    image: curlimages/curl:7.88.1@sha256:48318407b8d98e8c7d5bd4741c88e8e1a5442de660b47f63ba656e5c910bc3da
    
    variables:
        moduleName: gitlab-serverless-runner-manager
        moduleProvider: aws
        moduleVersion: ${CI_COMMIT_TAG}
        tokenHeader: 'JOB-TOKEN: ${CI_JOB_TOKEN}'
    
    script:
      - tar -czvf ${moduleName}.tar.gz --exclude ./.git .
      - curl
            --header "${tokenHeader}"
            --upload-file ${moduleName}.tar.gz
            --fail-with-body
            ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/terraform/modules/${moduleName}/${moduleProvider}/${moduleVersion}/file
    
    rules:
      - if: $CI_COMMIT_TAG